### ISSUE TITLE
Able to 'Win' when I find the lion first

### ISSUE THREAD

**Issue by vultuk** [FNuri/EscapeTheLion#1]
If the lion is found on my first click on the door, I can still continue to click on the doors. Although the doors do not reveal what is behind, the button text will change to 'You Won - Play Again?'

**Steps to re-create**
- Click on a door
- Find the Lion first
- Click on the two remaining doors
- Win the game regardless

**Comment by FNuri** [comment]
Thanks for pointing out. Yes, you are right. The button text should not change from 'Game Over! Play Again?' to 'You Won - Play Again?' when the lion is found. Will work on rectifying that. Appreciate your feedback!

**Comment by FNuri** [comment]
> If the lion is found on my first click on the door, I can still continue to click on the doors. Although the doors do not reveal what is behind, the button text will change to 'You Won - Play Again?'
> 
> **Steps to re-create**
> 
> * Click on a door
> * Find the Lion first
> * Click on the two remaining doors
> * Win the game regardless

Fixed the gameOver button code so that the button shows correct status/text. Thanks.
